version: "2.1"
services:
  couchdb:
    image: couchdb:1.7.1
    ports:
      - 5984:5984
    volumes:
      - "./couchdb/data:/opt/couchdb/data"
    
# Graph database may be used in the future
# neo4j:
#   image: neo4j:3.3
#   ports:
#     - 7474:7474
#     - 7687:7687
#   volumes:
#     - "./neo4j/data:/data"
